DROP VIEW IF EXISTS expenses;

CREATE VIEW expenses AS
SELECT
  ZINOUTCOME.ZTXDATESTR,
  CAST(substr(ZINOUTCOME.ZTXDATESTR, 1, 4) AS INTEGER) AS TXN_YEAR,
  ZINOUTCOME.ZCONTENT,
  ZINOUTCOME.ZAMOUNT AS SPENT_MYR,
  SUBSTR(ZINOUTCOME.ZCURRENCYUID, 5, 3) AS DEST_CURRENCY,
  PARENT_CATEGORY.ZNAME AS PARENT_CATEGORY_NAME,
  ZCATEGORY.ZNAME AS CATEGORY_NAME
FROM ZINOUTCOME
LEFT JOIN
  ZCATEGORY
  ON ZINOUTCOME.ZCATEGORYUID = ZCATEGORY.ZUID
LEFT JOIN
  ZCATEGORY AS PARENT_CATEGORY
  ON ZCATEGORY.ZPUID = PARENT_CATEGORY.ZUID
WHERE ZINOUTCOME.ZDO_TYPE = 1;
